"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar";
import { Toaster } from "react-hot-toast";
import Provider from "./components/Provider";
import SignUp from "./components/SignUp";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gray-500`}
        style={
          pathname === "/" || pathname === "/sign-up"
            ? {
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                height: "100vh",
              }
            : {}
        }
      >
        <Provider key={"jotai"}>
          <Toaster position="bottom-center" />
          <div className="flex">
            {pathname !== "/" && pathname !== "/sign-up" && <Sidebar />}
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
